### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by irshadmgs011** [mstrens/grbl_controller_esp32#11]
please add bluetooth connectivity feature

**Comment by mstrens** [comment]
I am not sure it is safe to control a CNC using bluetooth. Bluetooth is only for short distance.

**Comment by mstrens** [comment]
Bluetooth have been added in latest versions of the firmware but it can be used to communicate between the controller and GRBL (not between the PC and the controller).
Note: GRBL_ESP32 is a project that allows you to control GRBL from a bluetooth (e.g. android) device.
It can be used with the latest versions of my firmware.
For more info, look at www.makerfr.com
