### ISSUE TITLE
No WiFi with last update

### ISSUE THREAD

**Issue by Sp3cN4z** [mstrens/grbl_controller_esp32#13]
I updated my TFT with the newest firmware.
Of course I edited the config.h file.

My WiFi name consists of two words seperated by a space, such as:
word1 word2

The password consists of letters (big and small), numbers and special characters.

So my config.h looks like:

    // If wifi is used, set the parameter to identify the access point (= the router when ESP32_ACT_AS_STATION or the ESP32 when ESP32_ACT_AS_AP)
    #define MY_SSID "word1 word2" // replace by the name of your access point (when act as station) or the name you assign to your device (when act as acces point)

    // Only for ESP32_ACT_AS_STATION , set the password to get access to your access point (router)
    #define MY_PASSWORD "aBc1234?" // replace by the password of your access point (when act as station) or the password you want to use to protect your ESP32 (when act as acces point)
    // in this last case, password can remains empty
    // select your language between EN, FR, DE
    #define LANGUAGE DE 

Of course this are fictitious values but it should show the situation.
Please mention the " in which each value is - is it correct so?

I thought it must work like this but when I start my TFT sometimes allways show an error.
Either Error 1 "Expected cmd letter" or Error 2 "Bad number format".
As my WiFi doesn't work (as showed on the TFT) I think the errors have something to do with the WiFi problem.

**Comment by mstrens** [comment]
The errors you get are not wifi related.
They are sent by GRBL.
I expect that on power on there is some "noise" on the line between ESP32 and GRBL. GRBL interpret this as a character and in most cases, it does not fit with a valid Gcode command.
Just discard those error when they apear at power on.
To remove the error from the TFT, press the Info button and then the Back button.

When you press the Info button do you get an Ip adress? If yes, the wifi is OK;
Please note that the "wifi" icon on the TFT is not really related to the wifi but is green only when a telnet session is opened from the PC
