### ISSUE TITLE
Wifi Bridge trobles

### ISSUE THREAD

**Issue by achest** [mstrens/grbl_controller_esp32#15]
Hello!

I try to use esp8266 as SerialBrige to connect on Arduino Nano (Grbl). It not works with bCNC.

can you explain me, that's the difference between your Software and https://github.com/arkypita/ESP8266-SerialTelnet ?

Both do not implement  rfc2217 ? It likes similar to yours

your url looks like this : socket://ip:23 or rfc2217:// or some thing else? 

can you help me to find/write a library for my purpose? Thank you.

**Comment by mstrens** [comment]
Sorry, I have no experience with esp8266
