### ISSUE TITLE
Hardware recommendations

### ISSUE THREAD

**Issue by beckmx** [mstrens/grbl_controller_esp32#2]
Hello, I would like to implement your idea, and was looking at the hardware needs, do you have any links for the board, screen and pad?

**Comment by mstrens** [comment]
My project/code has been used by a group of makers for their CNC.
You can find a lot of info on this site:
https://www.makerfr.com/cnc/rs-cnc32/liste-des-pieces-rs-cnc32/

It is a french site but it contains an english section.
The project around ESP32 is quite new and not all documents are translated.
There are links to the devices (esp32 and tft) to buy on aliexpress.
The group has developed a pcb if you want; so you can just plug the ESP and TFT.
The project presented uses a STM32 to run GRBL but you can also use alternative (arduino uno, mega, ...) if you implement GRBL 1.1 version.
.
