### ISSUE TITLE
How can we make the telnet connection? 

### ISSUE THREAD

**Issue by MeKeCNC** [mstrens/grbl_controller_esp32#23]
How can we make the telnet connection? Is it necessary to write the server ip address to establish a connection?

**Comment by mstrens** [comment]
Here an extract from the readme:
In bCNC, select the "File" tab, and in the Serial part, in field Port, enter:\

for a USB connection : comX (where X is the com port assigned to ESP32 e.g. with Arduino)
for a Wifi (telnet) connection : socket://192.168.1.5:23 (where 192.168.1.5 has to be replaced by the IP adress assign to your ESP32)
