### ISSUE TITLE
support for 4 Inch HD 480x320 TFT Display with Touch Screen (for Rapberry Pi)

### ISSUE THREAD

**Issue by ao41tr** [mstrens/grbl_controller_esp32#24]
Hello, thank you for such a good project,
I have 4 Inch HD 480x320 TFT Display with Touch Screen for Rapberry Pi and I guess it is possible to use for your controller. This display does not have sd card option, so needed a seperate module. Maybe also some other Raspberry owners will be interested using their LCD hardware for cnc.
Could you tell or publish any solution?

Interface: SPI
Touch panel control chip: XPT2046
"https://www.elecrow.com/wiki/index.php?title=4_Inch_HD_480x320_TFT_Display_with_Touch_Screen_for_Rapberry_Pi"
![image](https://user-images.githubusercontent.com/25576357/99183571-f3bac200-274d-11eb-946f-3825d8a30717.png)
![image](https://user-images.githubusercontent.com/25576357/99183588-033a0b00-274e-11eb-899c-08d87d2bc268.png)

**Comment by mstrens** [comment]
I expect it should be possible to use this display.
Still I do not expect to modify the code for this model.
In the new version of the firmware, it is possible to use a 4" TFT with similar resolution but it is another model.
You could try using the last version of the firmware and modify the type of TFT controller according to your model (it requires to activate another line in the tft_espi library (in User_setup.h file)
