### ISSUE TITLE
support 4th axis?

### ISSUE THREAD

**Issue by irshadmgs011** [mstrens/grbl_controller_esp32#3]

**Comment by mstrens** [comment]
I could add support for 4th axis in the coming weeks.
Still it is not clear what I have to do.
At this stage I presume I have to:
- add 2 coordinates on the INFO screen (so also using a smaller font for the current 6 coordinates)
- add the buttons to move the 4th axis with the TFT
- allow to move the 4th axis with the Nunchuk
- add a SET button for the 4 axis
Do you see something more?

**Comment by mstrens** [comment]
Support for 4th axis has been added
