### ISSUE TITLE
Temporary force USB mode

### ISSUE THREAD

**Issue by thijs666** [mstrens/grbl_controller_esp32#30]
Is it possible to temporary force USB mode so I can use the CNC without a working touchscreen? I'm waiting for a replacement and need to use the CnC asap.

**Comment by mstrens** [comment]
Yes, it is possible.
In the .ino file, there is a line with:
//         printing status
uint8_t statusPrinting = PRINTING_STOPPED ;

Change it in
//         printing status
uint8_t statusPrinting = PRINTING_FROM_USB ;

**Comment by Oleg9965** [comment]
Hello! I really like your project. Is it possible to rotate the image by 180 degrees.

**Comment by mstrens** [comment]
Normally it is possible to rotate the image.
In file draw.cpp you have a line with 
tft.setRotation(1);

You can try to replace 1 by 3.

**Comment by Oleg9965** [comment]
Thanks!
