### ISSUE TITLE
When I repeatedly press Pause/Resume several times,it will stop sending gcode.

### ISSUE THREAD

**Issue by viewsat** [mstrens/grbl_controller_esp32#33]
Hello there:
When I repeatedly press Pause/Resume several times, it will stop sending gcode. Is this an error in my operation? Or is there an error in grbl_controller_esp32? I connect to grbl V1.1f (Arduino UNO).
![pause](https://user-images.githubusercontent.com/15762267/117533680-a6465000-b020-11eb-9e03-f26d4d7532e3.png)

**Comment by viewsat** [comment]
Pause Button test video
[https://youtu.be/5V1ZVn9fpcc](url)

**Comment by mstrens** [comment]
Thanks for reporting this.
I expect I know the reason.
I will try to find a solution.

**Comment by mstrens** [comment]
I put a new version on github that should fix this issue (I hope)

**Comment by viewsat** [comment]
> I put a new version on github that should fix this issue (I hope)

I tested the pause (hold) button of the new version, and there will be no problem of stopping sending gcode.
Thank you very much!
