### ISSUE TITLE
Error when setting axis to zero

### ISSUE THREAD

**Issue by williangomesa** [mstrens/grbl_controller_esp32#40]
Hi ! first of all thanks for this awesome work! I'm having a strange issue, I use the firmware to control a 4 axis hotwire machine, when I set all axis to zero(XYZA) mpos don't become zero and sometimes it affect when I load a file to run, what could I do to zero everithing ?

**Comment by mstrens** [comment]
This is not a bug.
Set XYZA (or only some axis) does not set mpos to zero but wpos. It send then command G10 L20 P1 X0 Y0 Z0 A0 (defined in config.h file)

mpos is set to zero when you perform a Home.
In fact in cnc mode, your gcode does not refer usually to machine position (mpos) but to work position (wpos).
Your Gcode will refers to wpos if you activate one offset coordinate. This firmware supposes that you use first offset coordinates(activated with G54)

**Comment by williangomesa** [comment]
Thanks !
