### ISSUE TITLE
can not flash 

### ISSUE THREAD

**Issue by jasinghuang** [mstrens/grbl_controller_esp32#6]
Arduino:1.8.10 (Mac OS X), 开发板："ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

"Wire.h" 对应多个库
 已使用： /Users/jasing/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/Wire
"SPI.h" 对应多个库
grbl_controller_esp32:61:19: error: SdFat.h: No such file or directory
 已使用： /Users/jasing/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/SPI
compilation terminated.
"FS.h" 对应多个库
 已使用： /Users/jasing/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/FS
"SPIFFS.h" 对应多个库
 已使用： /Users/jasing/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/SPIFFS
exit status 1
SdFat.h: No such file or directory

在文件 -> 首选项开启
“编译过程中显示详细输出”选项
这份报告会包含更多信息。

expect your help:)

Thank you~

**Comment by mstrens** [comment]
The project uses the Sdfat library.
You have to install it in your arduino IDE.
You can easily find on Internet how to install a library.

**Comment by jasinghuang** [comment]
> The project uses the Sdfat library.
> You have to install it in your arduino IDE.
> You can easily find on Internet how to install a library.

Thank you, I figured it out

**Comment by jasinghuang** [comment]
> The project uses the Sdfat library.
> You have to install it in your arduino IDE.
> You can easily find on Internet how to install a library.

But it can not show anything on the screen, but only white light.
![微信图片_20191031102411](https://user-images.githubusercontent.com/33535475/67913636-ac0bdb80-fbc8-11e9-94e9-bfe3c1998c9e.jpg)

![微信图片_20191031102402](https://user-images.githubusercontent.com/33535475/67913623-a7472780-fbc8-11e9-9ab8-0e0675c59884.jpg)

I wired according to your README.md.
expect your help,
thank you very much

**Comment by mstrens** [comment]
Some people reported similar issue (even no led or blinking led).
As far I know, the reason was a wrong board selected in the arduino IDE.
I used WEMOS LOLIN32 I think
