### ISSUE TITLE
Problem with TFT operation

### ISSUE THREAD

**Issue by maximius** [mstrens/grbl_controller_esp32#7]
Good afternoon

I'm trying to assemble the device you designed. ESP32 successfully firmware through Arduino IDE. 

If after loading ESP 32 to include without connected TFT, the serial monitor works according to the program.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/QNhwk9s/1.png" alt="1" border="0"></a>

If I connect a TFT, a cyclic error appears in the serial monitor.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/znDBnHh/2.png" alt="2" border="0"></a>

 Tried different versions of boards and memory volumes. Tried other boards as well. The result is the same. TFT 3.2" 320x240 ILI9341.
Connection according to the following scheme
<a href="https://ibb.co/rQJ1qp0"><img src="https://i.ibb.co/GdjbGMp/readme.png" alt="readme" border="0"></a><br /><a target='_blank' href='https://ru.imgbb.com/'>image share</a><br />

**Comment by mstrens** [comment]
The program works for sure. There are several users.

Continuous reset with ESP32 can occur when power supply is not strong/stable enough.
Wifi consumes a lot but only by peak.
Perhaps you are at the limit.
You can try 
- disabling the wifi (one parameter in config file)
- changing the power supply
- adding condensators on the 5V

**Comment by maximius** [comment]
Found the cause of the error. It turned out that one GND pin next to the V5 pin did not connect to the rest of the GND. He squandered the tension. Thanks for the help.
